version: 2
jobs:
  "3.5":
    docker:
    - image: python:3.5-slim
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install -r requirements.txt -r requirements-dev.txt
    - run:
        name: test
        command: |
          ~/repo/entry.sh test
    - run:
        name: build
        command: |
          ~/repo/entry.sh build
  "3.6":
    docker:
    - image: python:3.6-slim
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install -r requirements.txt -r requirements-dev.txt
    - run:
        name: test
        command: |
          ~/repo/entry.sh test
    - run:
        name: build
        command: |
          ~/repo/entry.sh build
#  "docker":
#    docker:
#    - image: docker
#    working_directory: ~/repo
#    steps:
#    - checkout
#    - setup_remote_docker:
#          docker_layer_caching: true
#    - run:
#        name: build and publish image
#        command: |
#          ~/repo/entry.sh docker-build && ~/repo/entry.sh docker-publish

workflows:
  version: 2
  build:
    jobs:
    - "3.5"
    - "3.6"
#    - "docker":
#        require: "3.6"